# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-Translate
version:      0.09
version_from: lib/Lingua/Translate.pm
installdirs:  site
requires:
    HTML::TokeParser:              2.19
    I18N::LangTags:                0.27
    LWP::UserAgent:                1.73
    Pod::Constants:                0.15
    Unicode::MapUTF8:              1.09

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
